# Site settings
title: CPR
email: your-email@domain.com
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/KACPR1
  - title: facebook
    url: https://www.facebook.com/kacpr?fref=ts
  - title: stack-overflow
    url: http://stackoverflow.com
  - title: bitbucket
    url: http://bitbucket.org
  - title: github
    url: http://github.com/kllh/kllh.github.io

# Postal address (add as many lines as necessary)
address:
  - line: 한국기술교육대학교
  - line: 충청남도 천안시 동남구
  - line: 병천면 충절로 1600 컴퓨터공학부

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
